notifications:
  on_success: never
  on_failure: never

language: generic
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    env:
      - PY_VERSION='3.6'
      - COMPLETE=true
  - os: linux
    dist: trusty
    sudo: false
    env:
      - PY_VERSION='3.7'
      - COMPLETE=false

install:
  - MINICONDA=Miniconda3-latest-Linux-x86_64.sh
  - wget https://repo.continuum.io/miniconda/$MINICONDA
  
  - bash $MINICONDA -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  - conda create -q -n gecos-env python=$PY_VERSION
  - conda install -n gecos-env  -c conda-forge -c anaconda  biotite numpy matplotlib scikit-image pytest sphinx numpydoc
  - source activate gecos-env

script:
  - python setup.py test

before_deploy:
  - if [ $COMPLETE == true ]; then python setup.py bdist_wheel; fi
  - if [ $COMPLETE == true ]; then python setup.py build_sphinx; fi
  - if [ $COMPLETE == true ]; then cd doc/_build; fi
  - if [ $COMPLETE == true ]; then mv html doc; fi
  - if [ $COMPLETE == true ]; then zip -r doc.zip doc; fi
  - if [ $COMPLETE == true ]; then cd ../..; fi

deploy:
  provider: releases
  api-key:
    secure: "gn53B3Ux6w7kKBnUDCz5oPx9OzRylQuKfbiGvcH/N04zAjOZp9OgTj9PlsJ+5uymIRufcYGDcWiAcwJllLXp3aT6G13dlyNmZvJ+wIATw4BLjAjiAFtsQiKNlCNtmTOGD0QczM/iFqGSDN2sWvET65zEVOaDgeEm51fnj8yawJ8Na3RzaNw51vYvM6vZTj38n46O+m6eMxivwdh42kFACw++/LKJAEenpJkTeGeGa8Kbra9HRFEyUQh60iYs930OcHmetgZ5g6C+QE1En4fO+a0KV5C0q06luZ/dp7KTODwOSgx2E6Hz0/imMnDHmfWefm0jMWijE1cZJBEgkUkr5J58JbI6syKC608YfQLTwjxQLioErLIwJW46xlV5hgpUmcLRAbED+sexcwGNJT0zuW1jnqKNEvOargYzfWrn+drQVCn3vLECH/S2qCgn80JH2rFA++WHoLmr1luShK7seF91a7zTamWy8u9uHvoDfjuc3eJh0MSMTDRigaGh6RnHIToaIcqcySUqm2L5ZF40c0pSBYSUmSxW+TuQiBy3EM4BcWDzm9K44/oRAAQ8FIHn7LIrqxlOA+47SrcQZHY/vcNG4KPDYZfKrZ2OK81cfV7ZwBtWKwrhJJejH4hdkyenQ6qVFtFFNFSI1OaqslNVtLq+tVp1t1ClKVsdCE7J7ek="
  file:
    - dist/*
    - doc/_build/doc.zip
  file_glob: true
  on:
    repo: biotite-dev/gecos
    tags: true
  skip_cleanup: true
