notifications:
  on_success: never
  on_failure: never

language: python
os: linux
dist: bionic
jobs:
  include:
  - python: "3.6"
    env: COMPLETE=false
  - python: "3.7"
    env: COMPLETE=false
  - python: "3.8"
    env: COMPLETE=true

install:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  - export PATH="~/.poetry/bin:$PATH"
  - poetry install

script:
  - pytest

before_deploy:
  - if [ $COMPLETE == true ]; then poetry build; fi
  - if [ $COMPLETE == true ]; then sphinx-build ./doc ./doc/_build/doc; fi
  - if [ $COMPLETE == true ]; then cd doc/_build; fi
  - if [ $COMPLETE == true ]; then zip -r doc.zip doc; fi
  - if [ $COMPLETE == true ]; then cd ../..; fi

deploy:
  provider: releases
  token:
    secure: "oiXNlW6bHYJ3x2YxWTBauYaRG60OgAGxfyMowfIwrRuF+pRhfY1lt2foAgsVK5kglXC3CVbyvQiv5+cr3oEEU4j1wpY1OGe5ehtJAnxuEqlew1rTQwetAEAGw018mKWNgT6GlHHiOPtcyppwnYBeMp6/Spqu1ALloWckndeyJ8SzPdemZyI4q7sFk9TOLFpP3xY8Hab8hQv/qrYihWyxkLxnidbvUiZw63dUCjN8LCzj+RByRRG/GtHtNTh/+YfnjP5WvYzxvjyLITz+KDoZhjB44cf/2hplzLXLdTx/Yr0Q3xeCKJeOm1mTi8zA2bx+fLIod+6vg4bIYk/80a5lP/9o1ynMr91FbF94OS/sP5H4GT0fHaaCfHoins/wIHZ+NALNqy6j4nzO5hYJxa46OZbOnxnfTkwbmDmRIcT36GKp+d1A965cuQhicT8Z8dF1mcyBujoBkqE3b/LDOZk3jR6grOObo0M0QVCJbb+UAtEa+hTkvOwGkZfxuciX0wVLhGdCROTGRYcl9yqkAlDufe6rxGi0FE04UzdJ6Ba7xb/S8cBXJ/VeYhj14CVAdH3ujDb72UTzqE7nJBFzrTh8FWYOPpjs1TL/lVDjsLDFXWsGNVk3XVIJu7bMIP200m50XWbObyDcuDECIRe1c6efdZSfCa78xfsKrtVpDJdYPOU="
  file:
    - dist/*
    - doc/_build/doc.zip
  file_glob: true
  on:
    repo: biotite-dev/gecos
    tags: true
  skip_cleanup: true
